os: linux
dist: xenial
language: php

php: 7.4

git:
  depth: 1

install:
  - composer install

jobs:
  include:
    - before_script:
        - pecl install pcov
    - script: composer phing ci

cache:
  directories:
    - $HOME/.composer/cache
